id: ai-pull-request-analysis
namespace: devplus

inputs:
  - name: pr_id
    type: STRING
  - name: pr_number
    type: INT
  - name: repo_id
    type: STRING
  - name: repo_owner
    type: STRING
  - name: repo_name
    type: STRING
  - name: pr_title
    type: STRING
  - name: pr_diff
    type: STRING
  - name: callback_url
    type: STRING

tasks:
  - id: analyze_with_gemini
    type: io.kestra.plugin.gemini.ChatCompletion
    apiKey: "{{ secret('GEMINI_API_KEY') }}"
    model: gemini-2.0-flash-exp
    messages:
      - type: USER
        content: |
          You are a code reviewer. Analyze the following Pull Request:

          Repository: {{ trigger.body.repo_owner }}/{{ trigger.body.repo_name }}
          PR #{{ trigger.body.pr_number }}: {{ trigger.body.pr_title }}

          Code Changes (Diff):
          ```diff
          {{ trigger.body.pr_diff }}
          ```

          Please provide a thorough code review in markdown format analyzing:
          1. Code quality and best practices
          2. Potential bugs or issues
          3. Security concerns
          4. Performance implications

          Provide a JSON response in the format:
          {
            "summary": "Detailed review summary with specific feedback in markdown format with proper headers and bullet points.",
            "decision": "APPROVE or REQUEST_CHANGES"
          }

  - id: callback_backend
    type: io.kestra.plugin.core.http.Request
    uri: "{{ trigger.body.callback_url }}"
    method: POST
    contentType: application/json
    body: |
      {
        "pr_id": "{{ trigger.body.pr_id }}",
        "raw_analysis": {{ outputs.analyze_with_gemini.predictions[0].content | json }}
      }

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: devplus-webhook-key
