id: ai-pull-request-analysis
namespace: devplus

inputs:
  - name: pr_id
    type: STRING
  - name: pr_number
    type: INT
  - name: repo_id
    type: STRING
  - name: repo_owner
    type: STRING
  - name: repo_name
    type: STRING
  - name: pr_title
    type: STRING
  - name: callback_url
    type: STRING

tasks:
  - id: fetch_diff
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    outputFiles:
      - "diff.txt"
    commands:
      - |
        OWNER="{{ trigger.body.repo_owner ?? inputs.repo_owner }}"
        REPO="{{ trigger.body.repo_name ?? inputs.repo_name }}"
        PR_NUMBER="{{ trigger.body.pr_number ?? inputs.pr_number }}"

        echo "Fetching diff for $OWNER/$REPO PR #$PR_NUMBER..." >&2

        # Fetch PR diff from GitHub API
        curl -s -L \
          -H "Accept: application/vnd.github.v3.diff" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER" > diff.txt

        if [ ! -s diff.txt ]; then
          echo "Error: Failed to fetch diff" >&2
          exit 1
        fi

        echo "Diff fetched successfully" >&2

  - id: analyze_with_gemini
    type: io.kestra.plugin.gemini.ChatCompletion
    apiKey: "{{ secret('GEMINI_API_KEY') }}"
    model: gemini-2.0-flash-exp
    messages:
      - type: USER
        content: |
          You are a code reviewer. Analyze the following Pull Request:

          Repository: {{ trigger.body.repo_owner ?? inputs.repo_owner }}/{{ trigger.body.repo_name ?? inputs.repo_name }}
          PR #{{ trigger.body.pr_number ?? inputs.pr_number }}: {{ trigger.body.pr_title ?? inputs.pr_title }}

          Code Changes (Diff):
          ```diff
          {{ read(outputs.fetch_diff.outputFiles['diff.txt']) }}
          ```

          Please provide a thorough code review analyzing:
          1. Code quality and best practices
          2. Potential bugs or issues
          3. Security concerns
          4. Performance implications
          5. Overall recommendation

          Provide a JSON response in the format:
          {
            "summary": "Detailed review summary with specific feedback",
            "decision": "APPROVE or REQUEST_CHANGES"
          }

  - id: callback_backend
    type: io.kestra.plugin.core.http.Request
    uri: "{{ trigger.body.callback_url ?? inputs.callback_url }}"
    method: POST
    contentType: application/json
    body: |
      {
        "pr_id": "{{ trigger.body.pr_id ?? inputs.pr_id }}",
        "raw_analysis": {{ outputs.analyze_with_gemini.predictions[0].content | json }}
      }

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: devplus-webhook-key
