id: ai-repo-analysis
namespace: devplus

inputs:
  - name: repo_id
    type: STRING
  - name: repo_owner
    type: STRING
  - name: repo_name
    type: STRING
  - name: readme
    type: STRING
  - name: file_tree
    type: STRING
  - name: callback_url
    type: STRING

tasks:
  - id: analyze_repo
    type: io.kestra.plugin.gemini.ChatCompletion
    apiKey: "{{ secret('GEMINI_API_KEY') }}"
    model: gemini-2.0-flash-exp
    messages:
      - type: USER
        content: |
          You are a senior software architect. Analyze the following repository:

          Repository: {{ trigger.body.repo_owner }}/{{ trigger.body.repo_name }}

          README:
          ```
          {{ trigger.body.readme }}
          ```

          File Structure:
          ```
          {{ trigger.body.file_tree }}
          ```

          Based on the README and file structure, provide an architectural analysis in markdown format with:
          1. Current architecture and technology stack
          2. Code organization and project structure
          3. Potential improvements or refactoring opportunities
          4. Security and scalability considerations
          5. Best practices alignment

          Provide your analysis in well-formatted markdown with headers, bullet points, and code blocks where appropriate.

  - id: callback_backend
    type: io.kestra.plugin.core.http.Request
    uri: "{{ trigger.body.callback_url }}"
    method: POST
    contentType: application/json
    body: |
      {
        "repo_id": "{{ trigger.body.repo_id }}",
        "raw_analysis": {{ outputs.analyze_repo.predictions[0].content | json }}
      }

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: devplus-repo-webhook-key
